var data = [
  {
    question: "What does HTML stand for?",
    option1: "Hypertext Machine Language",
    option2: "HyperText Markup Language",
    option3: "HighText Markup Language",
    answer: "HyperText Markup Language",
  },
  {
    question: "What does CSS stand for?",
    option1: "Cascading Style Sheets",
    option2: "Computer Style Sheets",
    option3: "Creative Style Sheets",
    answer: "Cascading Style Sheets",
  },
  {
    question: "What does JS stand for?",
    option1: " JavaServer",
    option2: "JavaScript",
    option3: "JustScript",
    answer: "JavaScript",
  },
  {
    question: " What does API stand for?",
    option1: "Application Programming Interface",
    option2: "Automated Programming Interface",
    option3: "Application Protocol Interface",
    answer: "Application Programming Interface",
  },
  {
    question: " What does SQL stand for?",
    option1: "Structured Query Language",
    option2: "Sequential Query Language",
    option3: "Simple Query Language",
    answer: "Structured Query Language",
  },
  {
    question: " What does DOM stand for?",
    option1: "Document Object Model",
    option2: "Data Object Model",
    option3: "Dynamic Object Model",
    answer: "Document Object Model",
  },
  {
    question: " What does HTTP stand for?",
    option1: "HyperText Transfer Protocol",
    option2: "Hyperlink Text Transfer Protocol",
    option3: "Hyper Transfer Text Protocol",
    answer: "HyperText Transfer Protocol",
  },
  {
    question: " What does URL stand for?",
    option1: "Universal Resource Locator",
    option2: "Uniform Resource Locator",
    option3: "Uniform Retrieval Locator",
    answer: "Uniform Resource Locator",
  },
  {
    question: " What does JSON stand for?",
    option1: "JavaScript Object Notation",
    option2: "JavaScript Online Notation",
    option3: "JavaScript Open Notation",
    answer: "JavaScript Object Notation",
  },
  {
    question: " What does FTP stand for?",
    option1: "File Transfer Protocol",
    option2: "File Text Protocol",
    option3: "File Transmission Protocol",
    answer: "File Transfer Protocol",
  },
];
